### ISSUE TITLE
PvP battles!

### ISSUE THREAD

**Issue by JoeScho** [pavellishin/slackidlerpg#11]
- Each player sums their item levels, and rolls [1..SUM] for SCORE. Higher SCORE wins.
- If a player's SCORE is SUM, it is a CRITICAL HIT - their opponent instantly loses a level, regardless of who wins!
- If the challenger wins, they get  (SCORE/SUM)% removed from their time to level.
- If the challenger loses, they get (SCORE/SUM)% added to their time to level.

---

- [x] Players must be at least level 5 before engaging in a battle, either as an attacker or defender
  - otherwise they have few items, and are very likely to roll a critical failure OR a critical hit
- [x] Announce battles
  - the score "won X to Y" is kind of ugly
  - > :crossed_swords: @cryokinetic has challenged @fancybone and *won* 45 to 39
  - Can the bot post a reply to the message, showing details about how the battle went down? Could solve the ugly X to Y, as well as show how a level 5 could take down a level 15.
- [x] Announce the levels of the participants
- [x] Award reduced TTL if winner
- [x] Add increased TTL if loser
- [x] Announce critical hits
- [x] Punish opponent on critical hit
  - Lose a level?
  - Lose an item?
  - Gain time to level?

---

- [x] Add critical failure (a roll of 0; need to make that the new minimum)
  - Lose a level? Seems harsh at higher levels. Maybe make this a low probability?
  - Lose an item?
  - Gain time to level?
- [ ] Add other triggers, besides leveling up, as source of combat.
  - Once an hour, random duel?
  - Team battles? Lowest-level players combine forces to take on a higher-level player?
  - Every time someone comes back from away, they fight, max one battle every 10 minutes?

**Comment by pavellishin** [comment]
Suggestions from #idlerpg-discussion:
 - battle every time someone comes back from away
  - but this would be very noisy; maybe limit away-battles to one very 10 minutes at most?

**Comment by pavellishin** [comment]
Implemented a part of this - battles now occur every time a player levels, but there's no consequences. (No time is gained or lost - critical hits are announced, but no consequences exist for those, either.)
