### ISSUE TITLE
Make sure level calculation is accurate

### ISSUE THREAD

**Issue by pavellishin** [pavellishin/slackidlerpg#31]
> Player @fancybone has levelled up to *level 1*! 11 minutes, 36 seconds until the next level.

I don't think that's right; it should be [600 * 1.16 ^ 1 (or 2?)](http://idlerpg.net/index.php), and that shouldn't be that much more than five minutes.

- [ ] Add some simple tests

**Comment by OuKevin** [comment]
Made the changes in #40
