### ISSUE TITLE
Init Player time_to_level

### ISSUE THREAD

**Issue by OuKevin** [pavellishin/slackidlerpg#58]
Current behavior:
Init player has a field "time_to_level": this.calculateTimeToLevel(2),
calculateTimeToLevel is calculated as Math.floor(300 * Math.pow(1.16, level-1)),
Initial leveling time would start with level offset of 1 equaling to 348(300 * 1.16).

It seems like it would make more sense to start off with no level offset so the time would start at
the initial value (300).

Proposed changes:
If calculateTimeToLevel should take the current player level then we can set calculateTimeToLevel(1).
If calculateTimeToLevel should take the next player level we can increase the offset from 1 to 2 in calculateTimeToLevel.

**Comment by pavellishin** [comment]
That's reasonable; feel free to open up a PR to implement this.
