### ISSUE TITLE
timeUntilLevelupString does not handle negative values "correctly"

### ISSUE THREAD

**Issue by pavellishin** [pavellishin/slackidlerpg#70]
`debug: Processing player T0B7KHWKG:U0B7PSQQY (fancybone): -247 seconds (-1 hours, -5 minutes, -7 seconds) to next level`

**Comment by ibokg** [comment]
@pavellishin Hello. I would like to know what exactly the function should return with negative values?

**Comment by pavellishin** [comment]
That's a good question :P I would say that it should return the same thing as a positive value, but with negatives - so `-60` should return `-1 minute`, and `-247` should return `-4 minutes, -7 seconds`. (If my math is right, there.)

**Comment by ibokg** [comment]
@pavellishin Can I try to do this?

**Comment by pavellishin** [comment]
Of course! Fork the project, and open up a pull request. I've got some guidelines in `CONTRIBUTING.md`. Let me know if you need help - I've got sporadic availability today, but I'll be around to answer questions every few hours.
