### ISSUE TITLE
Better display for "time to level", instead of just a number of seconds.

### ISSUE THREAD

**Issue by JoeScho** [pavellishin/slackidlerpg#9]
Currently, the user is just told how many seconds they have 'til they level up in `announceLevel`. It would be nice if it told them the time they have left in hours, minutes, seconds format.

e.g., instead of displaying `15711 seconds until the next level`, it should display `4 hours, 21 minutes, 51 seconds until the next level`.

**Comment by tjwhalen16** [comment]
I'll take this one.
